name: wf nelson

on:
  workflow_dispatch:
    inputs:
      lenguaje:
        description: Lenguaje de programacion usado
        required: true
        type: string
jobs:
  instalarDependencia:
    runs-on: ubuntu-latest
    if: inputs.lenguaje == 'java'
    steps:
      - name: instalar dependencias
        run: echo "dependencias"
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.repository.split('/')[1], 'bbog') && endsWith(github.repository.split('/')[1], '-testing')
    steps:
      - name: test
        run: echo "test"