name: wf nelson

on:
  workflow_dispatch:
    inputs:
      lenguaje:
        description: Lenguaje de programación usado
        required: true
        type: string

jobs:
  instalarDependencia:
    runs-on: ubuntu-latest
    if: inputs.lenguaje == 'java'
    steps:
      - name: instalar dependencias
        run: echo "dependencias"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer nombre del repositorio
        id: repo_name
        run: echo "repo_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Verificar nombre del repositorio
        if: startsWith(env.repo_name, 'bbog') && endsWith(env.repo_name, '-testing')
        run: echo "test"
